services:

  devcontainer:
    build:
      target: dev
    image: goat_book-devcontainer
    volumes:
      - ..:/workspaces
      - command-history-volume:/home/user/.history/

  app:
    build:
      target: app
    profiles:
      - app

volumes:
  command-history-volume:
