# Generated by Django 5.2.17 on 2026-08-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("lists", "0001_initial")]

    operations = [
        migrations.AddField(model_name="item", name="text", field=models.TextField(default=""))
    ]
