# Generated by Django 5.2.17 on 2026-09-01 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("lists", "0004_item_list")]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="list",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="lists.list",
            ),
        ),
        migrations.AlterUniqueTogether(name="item", unique_together={("list", "text")}),
    ]
