# Generated by Django 5.2.17 on 2026-09-02 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("lists", "0005_alter_item_list_alter_item_unique_together")]

    operations = [
        migrations.AlterModelOptions(name="item", options={"ordering": ("id",)}),
        migrations.AlterField(
            model_name="item",
            name="list",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="lists.list"
            ),
        ),
    ]
