# Generated by Django 5.2.17 on 2026-09-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("email", models.EmailField(max_length=254, primary_key=True, serialize=False))
            ],
        )
    ]
